[build]
  command = "chmod +x build.sh && ./build.sh"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"
  PIPENV_VENV_IN_PROJECT = "true"
  PYTHONUNBUFFERED = "1"
  LANG = "en_US.UTF-8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[build.processing]
  skip_processing = false
